# -*- encoding=utf8 -*-
__author__ = "ChenfengWu"
__desc__ = "must"
from airtest.core.api import *
auto_setup(__file__)
sys.path.append(os.path.dirname(os.path.abspath(__file__)).split("AirTest")[0])
from common.Heros import *

init_common = CommonAirTest.InitCommon()
GM, getUserInfo, userAccount, poco = init_common.heros_start()
globals().update(init_common.load_config(__file__))

print("userAccount是{}".format(userAccount))
GM.logout()
time.sleep(5)
poco = StdPoco()
poco.agent.c.call("AutoLogin", userAccount, "9601", False)

def button_name(name_btn):
    while not poco(name=name_btn).exists():
        time.sleep(2)
    poco(name=name_btn).click()  
    time.sleep(2)
    if name_btn == "expLabel":
        time.sleep(5)

def button_center_name(name_btn):
    while not poco(name=name_btn).exists():
        time.sleep(2)
    poco(name=name_btn).click((0.5,0.5))  
    time.sleep(2)
    
def wait_btn(name_btn):
    while not poco(name=name_btn).exists() or not poco(name="title").exists():
        time.sleep(5)   
        
def drag_to(posA,posB):
    posA.drag_to(posB,duration=1)
    time.sleep(2)

button_name("Button")
button_name("chouka")
button_name("gemLayer")
button_name("buyOneBtn")
button_name("name")
time.sleep(2)
button_name("touchLab")
button_name("instanceBtn")
button_name("building_icon7100103")
button_name("battleBtn")
wait_btn("countBtn")
button_name("expLabel")
# time.sleep(5)
button_name("monsterBtn")
button_center_name("102")
button_name("equipBg1")
button_name("upgradeStageBtn")
button_name("equip2")
button_name("upgradeStageBtn")
button_name("equip3")
button_name("boxIcon")
button_name("1")
button_name("building_icon7100104")
button_name("battleBtn")
button_name("<Label | Tag = -1, Label = '点击任意位置关闭'>")
wait_btn("countBtn")
button_name("expLabel")
# time.sleep(5)
button_name("closeBtn")
button_name("upgradeStageBtn")
button_name("equip4")
button_name("upgradeStageBtn")
poco(name="bg").offspring("closeBtn").click((0.5,0.5))
time.sleep(2)
button_name("updateStageBtn")
button_name("tishi")
button_name("instanceBtn")
button_name("Button")
button_name("building_icon7100105")
button_name("battleBtn")
button_name("<Label | Tag = -1, Label = '点击任意位置关闭'>")
wait_btn("countBtn")
button_name("expLabel")
# time.sleep(5)
button_name("Button")
button_name("reward1Btn")
time.sleep(2)
button_name("closeBtn")
button_name("monsterBtn")
button_center_name("101")
time.sleep(2)
button_name("name")
button_name("bagBtn")
button_name("flexoBtn")
button_name("monsterBtn")
button_center_name("101")
button_name("tab2")
button_name("upFiveTeamBtn")
button_name("closeBtn")
button_name("formationBtn")
drag_to(poco(name="item_0").focus('center'),poco(name="formation_icon_7").focus('center'))
button_name("btn_return")
button_name("instanceBtn")
button_name("Button")
button_name("Button")
time.sleep(5)
button_name("building_icon7100201")
button_name("battleBtn")
poco(name="layer_left").offspring("bitmap").click()
time.sleep(2)
poco(name="layer_right").offspring("bitmap").click((0.5,0.5))
time.sleep(2)
button_name("close")
drag_to(poco(name="formation_icon_8").focus('center'),poco(name="formation_icon_3").focus([0.5,1]))
button_name("btn_battle")
wait_btn("countBtn")
button_name("expLabel")
# time.sleep(5)
button_name("Button")
button_name("branch_icon_710021")
button_name("enterBtn")
button_name("btn_battle")
button_name("<Label | Tag = -1, Label = '点击任意位置关闭'>")
wait_btn("countBtn")
button_name("expLabel")
button_name("branch_icon_710121")
button_name("enterBtn")
button_name("Button")
button_name("building_icon7100202")
button_name("battleBtn")
button_name("btn_battle")
button_name("Button")
button_name("Button")
button_center_name("icon_4")
while not poco(name="guildeHelpMask").exists:
    time.sleep(2)
poco(name="guildeHelpMask").focus([0.5,0.6]).click()
time.sleep(2)
wait_btn("countBtn")
button_name("expLabel")
init_common.stop_game()

